# Generated by Django 5.1 on 2024-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_related_user_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproduct",
            name="discount",
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name="shopproduct",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shopproduct",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
